"""Generate concepts/preloader/_shared/brand-shape.js from concept 19's constants.

The mark geometry is long enough that hand-copying it between concepts invites
drift, which matters because the tail tip has been corrected against the
catalogue. This lifts the fitted curves out verbatim so both concepts read the
same source. Run again if concept 19's geometry is ever refitted.
"""

import re

SRC = 'concepts/preloader/19-gold-forge/gold-forge.js'
OUT = 'concepts/preloader/_shared/brand-shape.js'

src = open(SRC, encoding='utf-8').read()


def grab(name):
    m = re.search(r"var\s+%s\s*=\s*\n?\s*'([^']*)'" % name, src)
    if not m:
        raise SystemExit('could not find %s in %s' % (name, SRC))
    return m.group(1)


shape = grab('SHAPE')
fold_up = grab('FOLD_UPPER')
fold_lo = grab('FOLD_LOWER')

tip = re.match(r'M\s+(-?[\d.]+)\s+(-?[\d.]+)', shape)
tip_x, tip_y = tip.group(1), tip.group(2)

body = """/**
 * Shared brand mark geometry.
 *
 * GENERATED by brand/_gen_shared_shape.py from concept 19 — do not hand-edit.
 *
 * SHAPE is a least-squares fair-curve fit of the catalogue ribbon (88 control
 * points solved against 1200 samples of the bitmap trace), wound to start at the
 * bottom tail tip so a draw or a fill can run away from that point. FOLD_UPPER
 * and FOLD_LOWER are the shaded back faces of the twisted ribbon, meant to be
 * clipped to SHAPE and laid over the lit gradient.
 */
(function (global) {
  'use strict';

  global.BrandShape = {
    /* Artboard the coordinates are expressed in. */
    WIDTH: 564,
    HEIGHT: 630,

    /* Closed outline of the mark. */
    SHAPE:
      '%s',

    /* Shaded faces — clip to SHAPE before drawing. */
    FOLD_UPPER:
      '%s',
    FOLD_LOWER:
      '%s',

    /* First point of SHAPE: the tail tip, and the gate a pour grows from. */
    TIP: { x: %s, y: %s },
  };
})(window);
""" % (shape, fold_up, fold_lo, tip_x, tip_y)

open(OUT, 'w', encoding='utf-8', newline='\n').write(body)
print('wrote %s' % OUT)
print('  SHAPE      %d chars, tip (%s, %s)' % (len(shape), tip_x, tip_y))
print('  FOLD_UPPER %d chars' % len(fold_up))
print('  FOLD_LOWER %d chars' % len(fold_lo))
